PROCESS_ATTRIBUTE_TYPE.PERIOD=1;
PROCESS_ATTRIBUTE_TYPE.TIME_CAPACITY=1;
PROCESS_ATTRIBUTE_TYPE.ENTRY_POINT=1;
PROCESS_ATTRIBUTE_TYPE.STACK_SIZE=1;
PROCESS_ATTRIBUTE_TYPE.BASE_PRIORITY=1;
PROCESS_ATTRIBUTE_TYPE.DEADLINE=1;
PROCESS_ATTRIBUTE_TYPE.NAME='pkb';
