%function PROCESS_ATTRIBUTE_TYPE
global PROCESS_ATTRIBUTE_TYPE
PROCESS_ATTRIBUTE_TYPE.PERIOD=1;
PROCESS_ATTRIBUTE_TYPE.TIME_CAPACITY=2;
PROCESS_ATTRIBUTE_TYPE.ENTRY_POINT=1;
PROCESS_ATTRIBUTE_TYPE.STACK_SIZE=2;
PROCESS_ATTRIBUTE_TYPE.BASE_PRIORITY=1;
PROCESS_ATTRIBUTE_TYPE.DEADLINE_TYPE.DEADLINE=1;
PROCESS_ATTRIBUTE_TYPE.NAME='pkb';
%end